server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:campusconnect;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret: campusconnect-super-secret-key-2024-bengugdik-agu
  expiration: 86400000
