server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campusconnect?characterEncoding=UTF-8&useUnicode=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "SET client_encoding TO 'UTF8'"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          charSet: UTF-8
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
  cache:
    type: redis
  jackson: # Alttaki jackson ayarını olması gerektiği gibi buraya, spring'in altına taşıdık
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: campusconnect-super-secret-key-2024-bengugdik-agu
  expiration: 86400000

firebase:
  # Firebase kurulumu: Console'dan JSON indirip src/main/resources/firebase-service-account.json olarak kaydet
  service-account-path: classpath:firebase-service-account.json

logging:
  level:
    org.springframework.cache: DEBUG